language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
script: "./gradlew assemble"
after_success:
  - mv libray/build/outputs/aar/libray-release.aar android-slidinglayout-`git tag | tail -n 1`.aar
  - mv sample/build/outputs/apk/sample-debug.apk android-slidinglayout-sample-`git tag | tail -n 1`.apk
deploy:
  provider: releases
  api_key:
    secure: EnS/8nrJjLtUMFDho4VxGcpepEzZdtxuI9sH8+Fo2tRq1lVuceR4EdHY6ExAtYeKMo/WiSyJiwny8Xcpl1/zoDo88TiQWOorq6jENsAQHLyWfqSKfKM22x3J7T0NuFTU4CoSfuDlO/ilk/MUgY9mVlWhFWvKMCVOiNhGynYxVns=
  file:
    - "android-slidinglayout-`git tag | tail -n 1`.aar"
    - "android-slidinglayout-sample-`git tag | tail -n 1`.apk"
  skip_cleanup: true
  on:
    tags: true
